---
id: Auth
name: Auth
full: Authentication and user management library
description: >-
  A library that provides a common interface into various authentication
  backends.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Auth
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha1
  api: 3.0.0alpha1
state:
  release: stable
  api: stable
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Translation: ^2.2
      pear.horde.org/Horde_Util: ^2
    ext:
      hash: '*'
  optional:
    pear:
      pear.horde.org/Horde_Db: ^2
      pear.horde.org/Horde_History: ^2
      pear.horde.org/Horde_Lock: ^2
      pear.horde.org/Horde_Imap_Client: ^2
      pear.horde.org/Horde_Kolab_Session: ^2
      pear.horde.org/Horde_Ldap: ^2
      pear.horde.org/Horde_Imsp: ^2
      pear.horde.org/Horde_Http: ^2
      pear.horde.org/Horde_Test: ^2.1
      pecl.php.net/pam:
        version: '*'
        providesextension: pam
      pecl.php.net/sasl:
        version: '*'
        providesextension: sasl
    ext:
      ctype: '*'
      ftp: '*'
